name: Build Next.js frontend and deploy to AWS ECR
on:   
  push:
    branches: 
      - 'WI**'
      - dev
      - UAT
      - master

  pull_request:
    branches: 
      - dev
      - UAT
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test-alert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Snyk to check code vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
  
    - name: Send email on test failure
      if: failure()
      uses: dawidd6/action-send-mail@v2.2.0
      env:
        SENDER_EMAIL : ${{ vars.SENDER_EMAIL }}
        RECIPIENT_EMAIL : ${{ vars.RECIPIENT_EMAIL }}
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Test failed on ${{ github.repository }}'
        body: 'The test suite failed for ${{ github.repository }}'
        to: ${{ env.RECIPIENT_EMAIL }}
        from: ${{ env.SENDER_EMAIL }}

  build-and-deploy-uat:
    if: github.event_name == 'push' && github.ref == 'refs/heads/UAT'

    needs: test-alert
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECS_REGISTRY : ${{ secrets.ECS_REGISTRY }}
      CLUSTER_NAME_UAT : ${{ vars.CLUSTER_NAME_UAT }}
      SERVICE_NAME_UAT : ${{ vars.SERVICE_NAME_UAT }}
      TASK_DEFINITION_UAT : ${{ vars.TASK_DEFINITION_UAT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.FOTOPIE_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.FOTOPIE_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build docker image
      env: 
        BACKEND_API: ${{ secrets.BACKEND_API }}
        Get_Synonyms_API_Prefix: ${{ secrets.GET_SYNONYMS_API_PREFIX }}
        
      run: |
        docker build \
        --build-arg BACKEND_API=$BACKEND_API \
        --build-arg Get_Synonyms_API_Prefix=$Get_Synonyms_API_Prefix \
        -t ${{ env.ECS_REGISTRY }}/fotopie-fed-uat:latest .
   
    - name: Push docker image to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECS_REGISTRY }}
        docker push ${{ env.ECS_REGISTRY }}/fotopie-fed-uat:latest

    - name: Update ECS service
      run: |
          aws ecs update-service \
          --cluster $CLUSTER_NAME_UAT \
          --service $SERVICE_NAME_UAT \
          --task-definition $TASK_DEFINITION_UAT \
          --force-new-deployment

  build-and-deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test-alert
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECS_REGISTRY : ${{ secrets.ECS_REGISTRY }}
      CLUSTER_NAME_PROD : ${{ vars.CLUSTER_NAME_PROD }}
      SERVICE_NAME_PROD : ${{ vars.SERVICE_NAME_PROD }}
      TASK_DEFINITION_PROD : ${{ vars.TASK_DEFINITION_PROD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.FOTOPIE_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.FOTOPIE_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build docker image
      env: 
        BACKEND_API: ${{ secrets.BACKEND_API }}
        Get_Synonyms_API_Prefix: ${{ secrets.Get_Synonyms_API_Prefix }}

        
      run: |
       docker build \
       --build-arg BACKEND_API=$BACKEND_API \
       --build-arg Get_Synonyms_API_Prefix=$Get_Synonyms_API_Prefix \
       -t ${{ env.ECS_REGISTRY }}/fotopie-fed-prod:latest .

    - name: Push docker image to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION}}  | docker login --username AWS --password-stdin ${{ env.ECS_REGISTRY }}
        docker push ${{ env.ECS_REGISTRY }}/fotopie-fed-prod:latest
   
    - name: Update ECS service
      run: |
          aws ecs update-service \
          --cluster $CLUSTER_NAME_PROD \
          --service $SERVICE_NAME_PROD \
          --task-definition $TASK_DEFINITION_PROD \
          --force-new-deployment
  